### ISSUE TITLE
Score icons should give differentiable feedback

### ISSUE THREAD

**Issue by dseemann** [LUKKIEN/wagtail-marketing-addons#1]
As of now, scores are displayed on a range of four emojis: 😏 😱 😢 😄

Without a legend or a title it is quite hard to see if the score is good or bad.

Possible solutions could be a change to a star-based (e.g. ⭐️-⭐️⭐️⭐️⭐️) or numerical (e.g. 0/10 - 10/10) rating

**Comment by jjanssen** [comment]
Hi @5in4, thanks for already taking a look at this! Would not have guessed I would get a response so quickly after publishing.

I agree that it might be difficult to understand. I'm more in favour of the star rating as its more of an indication. A numerical rating would more or less imply a "perfect" SEO score, yet this tool just gives an indication whether somebody is on the right track. 

I'm curious for other suggestions as wel 👐

**Comment by jjanssen** [comment]
My thought is to fix this by making it a configurable setting for the next version. Hopefully I'll get to it sometime soon, otherwise I'm happy to accept a PR for this.

**Comment by BramManuel** [comment]
Good Solution for this long-lasting Issue!

**Comment by jjanssen** [comment]
Fixed with b707649 Thanks @5in4 for the report and your patience.
I'll make an official PyPi release this week.
