### ISSUE TITLE
Add site as an option for bulk redirect import

### ISSUE THREAD

**Issue by jjanssen** [LUKKIEN/wagtail-marketing-addons#8]
Currently there is no way to connect a list of redirects to a specific or all sites. This in inconvenient when having multiple sites available within in the same platform.

**Comment by BramManuel** [comment]
@jjanssen can you assign me to this issue?

**Comment by BramManuel** [comment]
#11 Solves this issue.

**Comment by jjanssen** [comment]
Merged with 84af6f5
